version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/static
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
    depends_on:
      - app

volumes:
  static: